"""Base LLM Client interface."""

from abc import ABC, abstractmethod
from typing import Any


class BaseLLMClient(ABC):
    """Abstract base class for all LLM client providers."""

    @abstractmethod
    async def generate(
        self,
        prompt: str,
        system_prompt: str | None = None,
        response_schema: Any | None = None,
    ) -> str:
        """Asynchronously generate response text or JSON from a prompt, supporting system prompt and JSON schema.

        Args:
            prompt: The user prompt to send to the model.
            system_prompt: Optional system prompt to instruct the model.
            response_schema: Optional Pydantic model class to enforce JSON output structure.

        Returns:
            The raw text generated by the model (JSON formatted if response_schema is provided).
        """
        pass
